# Generated by Django 4.2 on 2025-09-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='co_author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
