# Generated by Django 4.2 on 2025-09-06 20:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_thesis_co_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='RejectedThesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_submission_id', models.PositiveIntegerField(blank=True, help_text='ID of original submission', null=True)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('abstract', models.TextField(blank=True)),
                ('thesis_type', models.CharField(blank=True, max_length=100)),
                ('specialization', models.CharField(blank=True, max_length=120)),
                ('file', models.FileField(blank=True, null=True, upload_to='thesis_files/rejected/')),
                ('approval_sheet', models.FileField(blank=True, null=True, upload_to='thesis_files/rejected_approval_sheets/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection')),
                ('rejected_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.course')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.department')),
                ('original_submitter', models.ForeignKey(blank=True, help_text='Original submitter of this thesis', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_submissions', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, help_text='Admin who rejected this submission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_theses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rejected Thesis',
                'verbose_name_plural': 'Rejected Theses',
                'ordering': ['-rejected_at'],
            },
        ),
    ]
