# Generated by Django 4.2 on 2025-09-06 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_submission_status_rejectedthesis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-created_at'], 'verbose_name': 'Pending Submission', 'verbose_name_plural': 'Pending Submissions'},
        ),
        migrations.AlterModelTable(
            name='submission',
            table='main_pending_submission',
        ),
    ]
