# Generated by Django 4.2 on 2025-09-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_submission_options_alter_submission_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='co_authors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='submission',
            name='co_supervisor_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='submission',
            name='co_supervisor_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='submission',
            name='expected_completion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='submission',
            name='research_category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='submission',
            name='supervisor_department',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='submission',
            name='supervisor_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='submission',
            name='supervisor_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='submission',
            name='supervisor_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='thesis',
            name='co_authors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='thesis',
            name='co_supervisor_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='thesis',
            name='co_supervisor_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='thesis',
            name='expected_completion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thesis',
            name='keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='thesis',
            name='research_category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='thesis',
            name='supervisor_department',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='thesis',
            name='supervisor_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='thesis',
            name='supervisor_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='thesis',
            name='supervisor_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
