# Generated by Django 4.2 on 2025-09-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_submission_co_authors_submission_co_supervisor_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='review_state',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready_for_approval', 'Ready to be approved'), ('recommend_reject', 'Recommend reject')], default='pending', max_length=30),
        ),
    ]
