# Generated by Django 4.2 on 2025-09-17 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_downloadlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='co_authors',
        ),
        migrations.RemoveField(
            model_name='thesis',
            name='co_author',
        ),
        migrations.RemoveField(
            model_name='thesis',
            name='co_authors',
        ),
        migrations.CreateModel(
            name='SubmissionCoAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('student_id', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_authors', to='main.submission')),
            ],
        ),
        migrations.CreateModel(
            name='CoAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('student_id', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_authors', to='main.thesis')),
            ],
        ),
    ]
