# Generated by Django 4.2 on 2026-03-07 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='lc_classification',
            field=models.CharField(blank=True, help_text='Library of Congress Classification', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='thesis',
            name='lc_classification',
            field=models.CharField(blank=True, help_text='Library of Congress Classification', max_length=100, null=True),
        ),
    ]
