# Generated by Django 4.2 on 2026-03-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_submission_lc_classification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminStaff',
            fields=[
                ('admin_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Admin Staff',
                'verbose_name_plural': 'Admin Staffs',
            },
        ),
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('librarian_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Librarian',
                'verbose_name_plural': 'Librarians',
            },
        ),
    ]
