# Generated by Django 4.2 on 2026-03-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_adminstaff_librarian'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='full_text',
            field=models.TextField(blank=True, help_text='Stored full text of the PDF for deep search indexing', null=True),
        ),
    ]
