# Generated by Django 4.2 on 2026-04-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_thesis_full_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Hides the study from public search but preserves all metadata'),
        ),
    ]
