# Generated by Django 4.2 on 2026-07-03 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0014_thesis_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='coauthor',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_authored_theses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submissioncoauthor',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_authored_submissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
