name: CI with MariaDB

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

jobs:
  test:
    runs-on: ubuntu-latest


    strategy:
      fail-fast: false
      matrix:
        testcase:
          - main.tests.AuthTestCase.test_tc001_login_valid
          - main.tests.AuthTestCase.test_tc002_signup_valid
          - main.tests.SearchFilterTestCase.test_tc003_search_title_author_keyword
          - main.tests.SearchFilterTestCase.test_tc004_filter_by_category_year_author
          - main.tests.SubmissionStagesTestCase.test_tc005_basic_info_stage
          - main.tests.SubmissionStagesTestCase.test_tc006_thesis_details_stage
          - main.tests.SubmissionStagesTestCase.test_tc007_file_upload_stage
          - main.tests.SubmissionStagesTestCase.test_tc008_supervisor_info_stage
          - main.tests.SubmissionStagesTestCase.test_tc009_review_and_submit_stage
          - main.tests.AdminPanelTestCase.test_tc010_audit_logs
          - main.tests.AdminPanelTestCase.test_tc011_groups_and_permissions
          - main.tests.AdminPanelTestCase.test_tc012_create_admin_user
          - main.tests.AdminPanelTestCase.test_tc013_add_category
          - main.tests.AdminPanelTestCase.test_tc014_add_course
          - main.tests.AdminPanelTestCase.test_tc015_add_submission

    services:
      mariadb:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: thesis_library
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h127.0.0.1 -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    env:
      DJANGO_SETTINGS_MODULE: thesis_site.settings
      MYSQL_HOST: 127.0.0.1
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: thesis_library
      MYSQL_PORT: 3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for DB
        run: |
          until mysqladmin ping -h127.0.0.1 -uroot -proot --silent; do
            echo "Waiting for database..."
            sleep 3
          done

      - name: Ensure database exists
        run: |
          mysql -h127.0.0.1 -uroot -proot -e "CREATE DATABASE IF NOT EXISTS thesis_library;"

      - name: Run migrations
        run: python manage.py migrate

      - name: Run tests
        run: python manage.py test ${{ matrix.testcase }}

